version: '2'

services:
  angular-demo:
    image: nginx
    ports:
      - "3000:3000"
    volumes:
      - ./conf/proxy.nginx.conf:/etc/nginx/nginx.conf:ro
    command: ["nginx", "-g", "daemon off;"]
    container_name: heroes-api
